.macro_const DEC_ROUND_CEILING	0
.macro_const DEC_ROUND_UP	1
.macro_const DEC_ROUND_HALF_UP	2
.macro_const DEC_ROUND_HALF_EVEN	3
.macro_const DEC_ROUND_HALF_DOWN	4
.macro_const DEC_ROUND_DOWN	5
.macro_const DEC_ROUND_FLOOR	6
.macro_const DEC_ROUND_05UP	7
.macro_const DEC_ROUND_MAX	8
